name: Scheduled Stock Report
on:
  schedule:
    # 7:00 AM IST is 1:30 AM UTC
    - cron: '30 1 * * 1-5'
    # 8:00 PM IST is 2:30 PM UTC
    - cron: '30 14 * * 1-5'
  workflow_dispatch: # This adds a "Run Now" button for testing

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install yfinance

      - name: Run my script
        # --- ADD THESE TWO LINES BELOW ---
        env:
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        # ---------------------------------
        run: python main.py
