name: Institutional Stock Intelligence Report

on:
  schedule:
    - cron: '30 4 * * 1-5'  # 10:00 AM IST
    - cron: '30 13 * * 1-5' # 7:00 PM IST
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Analysis & Charting Libraries
        run: pip install yfinance requests mplfinance pandas
      - name: Execute Pipeline
        env:
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python main.py
